FROM ubuntu:latest

RUN apt-get update && apt-get -y install python-dev python-pip libxml2-dev libxslt1-dev zlib1g-dev libffi-dev libssl-dev cron
RUN pip install --upgrade pip
RUN pip install Scrapy

